### ISSUE TITLE
PHP 8 compatibility?

### ISSUE THREAD

**Issue by earnjam** [liran-co/laravel-notification-subscriptions#11]
I haven't source dived to check on this, but is this package compatible with PHP 8? It's locked into the 7.x branch because of the composer settings, so it's throwing a warning when I try to update to PHP 8. 

I was wondering if it's just a case of needing to add that to `composer.json` or if there are things that need to be changed in the code.

**Comment by liran-co** [comment]
Added support for PHP 8: https://github.com/liran-co/laravel-notification-subscriptions/releases/tag/v1.3.
